services:

  koha:
    build:
      context: .
    container_name: koha
    restart: unless-stopped
    cap_add:
      - SYS_NICE
      - DAC_READ_SEARCH
    depends_on:
      - koha-db
    environment:
      DB_HOST: koha-db
      DB_ROOT_PASSWORD: secret
      KOHA_TRANSLATE_LANGUAGES: "es-ES,en"
      LIBRARY_NAME: biblioteca
      INTRAPORT: 8080
    ports:
      - "80:80"
      - "8080:8080"

  koha-db:
    container_name: koha-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - koha-datos:/var/lib/mysql
    image: mariadb:10.3

  memcached:
    command: memcached -m 64m
    container_name: memcached
    restart: unless-stopped
    image: memcached

volumes:
  koha-datos:
    external: true